/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Conexao;
import Controller.ControleGasto;
import Controller.Tabela;
import Model.ModeloGasto;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Willian
 */
public class Gasto extends javax.swing.JFrame {
    Conexao conBanco = new Conexao();
   
    /**
     * Creates new form Gasto
     */
    public Gasto() throws ParseException {
        initComponents();
        conBanco.conexao();
        
        java.util.Date d = new java.util.Date();
        
        Calendar c = Calendar.getInstance();
       
        c.setTime(d);
       

        SimpleDateFormat df1 = new SimpleDateFormat("dd/MM/yyyy");
       

        String data = df1.format(c.getTime());
        txtdata.setText(data);

        
        
        //MaskFormatter data = new MaskFormatter("##/##/####");
        //txtdata.setFormatterFactory(new DefaultFormatterFactory(data));
        preencherTabela("select g.id_gasto,g.data,g.valor, c.nome, t.nomet ,g.obs from gasto g inner join categoria_gasto c on g.id_categoria=c.id_categoria inner join tipo_gasto t on g.id_tipo_categoria=t.id_tipo");
        
        
        try {
            String saldo ="select * from saldo_atual";
            conBanco.executarpesquisa(saldo);
            conBanco.rs.last();
            txtsaldo.setText(String.valueOf(conBanco.rs.getFloat("valor")));
            String sql ="SELECT * FROM categoria_gasto";
            conBanco.executarpesquisa(sql);
            conBanco.rs.first();
            do{
                combocategoria.addItem(conBanco.rs.getString("nome"));
                
            }while(conBanco.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no combo categoria"+ex);
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        combocategoria = new javax.swing.JComboBox<>();
        txtobs = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        txtdata = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtsaldo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("OBS:");

        jLabel2.setText("Valor:");

        jLabel3.setText("Data:");

        jLabel4.setText("tipo:");

        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoria:");

        combocategoria.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                combocategoriaMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                combocategoriaMouseMoved(evt);
            }
        });
        combocategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combocategoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combocategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                combocategoriaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                combocategoriaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                combocategoriaMouseReleased(evt);
            }
        });
        combocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocategoriaActionPerformed(evt);
            }
        });

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsalvar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2)))
                    .addComponent(txtobs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addComponent(btnsalvar)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel6.setText("Saldo:");

        txtsaldo.setText("0");

        jLabel8.setText("Cadastros de Gastos");

        jLabel9.setText("Todos os Gastos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsaldo)
                        .addGap(282, 282, 282))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtsaldo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        try {
            // TODO add your handling code here:
            ModeloGasto mod = new ModeloGasto();
            
            String sql ="Select * from categoria_gasto where nome='"+combocategoria.getSelectedItem()+"'";
            conBanco.executarpesquisa(sql);
            conBanco.rs.first();
            mod.setId_categoria(conBanco.rs.getInt("id_categoria"));
            
            String sql1 ="Select * from tipo_gasto where nomet='"+combotipo.getSelectedItem()+"'";
            conBanco.executarpesquisa(sql1);
            conBanco.rs.first();
            mod.setId_tipo(conBanco.rs.getInt("id_tipo"));
            String sql2 = "SELECT * from saldo_atual";
            conBanco.executarpesquisa(sql2);
            conBanco.rs.last();
            float saldo1 = conBanco.rs.getFloat("valor");
            float gasto = Float.parseFloat(txtvalor.getText());  
            
            mod.setSaldo(saldo1 - gasto);
            mod.setData(txtdata.getText());
            mod.setObs(txtobs.getText());
            mod.setValor(Float.parseFloat(txtvalor.getText()));
            
            
            ControleGasto obj = new ControleGasto();
            obj.inserir(mod);
            obj.inserirSaldo(mod);
            String saldo ="select * from saldo_atual";
            conBanco.executarpesquisa(saldo);
            conBanco.rs.last();
            txtsaldo.setText(String.valueOf(conBanco.rs.getFloat("valor")));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro no botão salvar:" +ex);
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void combocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocategoriaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_combocategoriaActionPerformed

    private void combocategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocategoriaMouseClicked
      
       
    }//GEN-LAST:event_combocategoriaMouseClicked

    private void combocategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocategoriaMouseEntered
        try {                                            
            String sql1 ="Select * from categoria_gasto where nome='"+combocategoria.getSelectedItem()+"'";
            conBanco.executarpesquisa(sql1);
            conBanco.rs.first();
                    try {
                        
                        combotipo.removeAllItems();
                        String sql ="SELECT * FROM tipo_gasto where fk_id_categoria='"+conBanco.rs.getInt("id_categoria")+"'";
                        conBanco.executarpesquisa(sql);
                        conBanco.rs.first();
                        do{
                            combotipo.addItem(conBanco.rs.getString("nomet"));
                            
                        }while(conBanco.rs.next());
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Erro no segundo select"+ex);
                    }
                    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro no primeiro select:" +ex);
        }
    }//GEN-LAST:event_combocategoriaMouseEntered

    private void combocategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocategoriaMouseExited
         
    }//GEN-LAST:event_combocategoriaMouseExited

    private void combocategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocategoriaMousePressed
        
    }//GEN-LAST:event_combocategoriaMousePressed

    private void combocategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocategoriaMouseReleased
         
    }//GEN-LAST:event_combocategoriaMouseReleased

    private void combocategoriaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocategoriaMouseMoved
        
    }//GEN-LAST:event_combocategoriaMouseMoved

    private void combocategoriaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocategoriaMouseDragged
        
    }//GEN-LAST:event_combocategoriaMouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tipo t = new Tipo();
        t.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Categoria c = new Categoria();
        c.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
        public void preencherTabela(String sql){
         ArrayList dados = new ArrayList();
            String[] Colunas = new String[] {"Código", "Valor", "Data","Categoria","Tipo","OBS"}; 
            conBanco.executarpesquisa(sql);
        try {
            conBanco.rs.first();
            do{
                dados.add(new Object[]{conBanco.rs.getInt("id_gasto"),conBanco.rs.getString("valor"),conBanco.rs.getString("data"),conBanco.rs.getString("nome"),conBanco.rs.getString("nomet"),conBanco.rs.getString("obs")});
            }while(conBanco.rs.next());
        } catch (SQLException ex) {
         //   JOptionPane.showMessageDialog(null,"Erro no ArryList");
        }
            Tabela modelo= new Tabela(dados , Colunas);
            tabela.setModel(modelo);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(75);
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(75);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(80);
            tabela.getColumnModel().getColumn(3).setResizable(false);
            tabela.getColumnModel().getColumn(4).setPreferredWidth(70);
            tabela.getColumnModel().getColumn(4).setResizable(false);
            tabela.getColumnModel().getColumn(5).setPreferredWidth(130);
            tabela.getColumnModel().getColumn(5).setResizable(false);
            
            tabela.getTableHeader().setReorderingAllowed(false);
            tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
            tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Gasto().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Gasto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox<String> combocategoria;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JTextField txtobs;
    private javax.swing.JLabel txtsaldo;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
